name: Run Main Model

on: workflow_dispatch

jobs:
  mlflowprojectrun:
    runs-on: macos-latest
    name: Run MLFlow Projects
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3.1.4
        with:
          python-version: '3.9.7' 
      - name: Install python version
        uses: gabrielfalcao/pyenv-action@v11
      # - name: Install Dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      # - name: Install PyEnv & Restart ZSH Shell
      #   run: |
      #     echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshrc
      #     echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshrc
      #     echo 'eval "$(pyenv init -)"' >> ~/.zshrc
      #     exec "$SHELL"

      - name: Check PyEnv version
        run: |
          pyenv --version
      # - name: Run Model Using MLproject File
      #   run: |
      #     mlflow run .
