name: Run Main Model

on: workflow_dispatch

jobs:
  mlflowprojectrun:
    runs-on: macos-latest
    name: Run MLFlow Projects
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3.1.4
        with:
          python-version: '3.9.7' 
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Model Using MLproject File
        run: |
          mlflow run . --env-manager=local
